name: CI/CD - Build, Test & Deploy sur GitHub Pages

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v7

      - name: Vérifier que index.html existe
        run: test -f index.html

      - name: charger les fichiers
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Télécharger l'artefact de build
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: .

      - name: Valider le HTML (W3C)
        uses: Cyb3r-Jak3/html5validator-action@v7
        with:
          root: .

      - name: Vérifier les liens cassés
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress './**/*.html'
          fail: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Télécharger l'artefact de build
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: .

      - name: Préparer les fichiers pour GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4